spring.application.name=crms-backend
spring.data.mongodb.uri=mongodb+srv://balasastha85266_db_user:Balasastha123@team06.c3h61lf.mongodb.net/crms_db?appName=Team06
spring.data.mongodb.auto-index-creation=true

# Server Port
server.port=8080

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO

# JWT Secret (This should be in environment variables in production)
crms.app.jwtSecret=VGhpc0lzQVN0cm9uZ0Vub3VnaFNlY3JldEtleUZvckpXVEdlbmVyYXRpb24yMDI0IQ==
crms.app.jwtExpirationMs=86400000
